version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
